### ISSUE TITLE
Revise Rago PvM Ability Rotations

### ISSUE THREAD

**Issue by Tjzabel** [gaasha/Vorago-Strategies#1]
## Description

Rago PvM ability rotations are out of date. We need to fix the bot formatting to make it more clear what abilities are being used, and when. This will help make rotations easier to read, and more beginner-friendly.

#### Phase 1
- [x] P1 

#### Phase 3
- [x] Ceilings
- [x] Scopulus
- [x] Vitalis
- [x] Green Bomb
- [x] Team Split
- [x] The End

#### Phase 5
- [x] Late ult (cade rot)
- [x] Non-Team Split (0 link)
- [x] Team Split (0 link)

------

#### Phase 1
- [x] P1 

#### Phase 3
- [x] Ceilings
- [x] Scopulus
- [x] Vitalis
- [x] Green Bomb
- [x] Team Split
- [x] The End

#### Phase 5
- [x] Cade rot
- [x] Non-Team Split (0 link)
- [x] Team Split (0 link)

------

#### Phase 1
- [x] P1 

#### Phase 3
- [x] Ceilings
- [x] Scopulus
- [x] Vitalis
- [x] Green Bomb
- [x] Team Split
- [x] The End

#### Phase 5
- [x] Cade rot
- [x] Non-Team Split (0 link)
- [x] Team Split (0 link)
